### ISSUE TITLE
urllib2 404 client error

### ISSUE THREAD

**Issue by JimChrModder** [ytisf/theZoo#119]
I think that pypi.org has changed file's name.
But there are 3 different files which contain urllib2.
I think that this is the updated one: https://pypi.org/simple/urllib2-file/
If so,the fix is just to edit the requirements.txt first line from "urllib2" to "urllib2-file"

**Comment by mdenzel** [comment]
Also pyzipper seems to be missing

**Comment by Morsmalleo** [comment]
> Also pyzipper seems to be missing

I'm pretty sure thats been replaced with Pyminizip
