### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [ytisf/theZoo#124]
sMMs              oMMy                                                                                :ooooo/        /ooooo:
        ```+MMd````````hMMo```
        oNNNMMMNNNNNNNNMMMNNNs
     /oodMMdooyMMMMMMMMyoodMMdoo/       theZoo 0.6.0 'Moat'
  `..dMMMMMy. :MMMMMMMM/  sMMMMMm..`     DB ver. 1567586699000

  dmmMMMMMMNmmNMMMMMMMMNmmNMMMMMMmmm
  NMMyoodMMMMMMMMMMMMMMMMMMMMdoosMMM    https://github.com/ytisf/theZoo
  NMM-  sMMMNNNNNNNNNNNNNNNMMy  .MMM
  NMM-  sMMy``````````````sMMy  .MMM
  ooo.  :ooooooo+    +ooooooo/  `ooo
           /MMMMN    mMMMM+
                                 authors: Yuval Nativ, Lahad Ludar, 5fingers
                                 maintained by: Shahak Shalev, Yuval Nativ
                                 github: https://github.com/ytisf/theZoo

mdb #> search android
+-----+------------+----------+--------------+----------+---------------------+
| #   | Type       | Language | Architecture | Platform | Name                |
+-----+------------+----------+--------------+----------+---------------------+
| 40  | virus      | bin      | arm          | android  | Android.VikingHorde |
| 49  | botnet     | apk      | arm          | android  | Android Spy 29      |
| 100 | trojan     | apk      | arm          | android  | Dendroid            |
| 162 | trojan     | java     | arm          | android  | Mazar               |
| 163 | ransomware | java     | arm          | android  | andr0id_l0cker      |
| 175 | trojan     | java     | arm          | android  | Skygofree           |
| 192 | trojan     | multi    | arm          | android  | Dendroid            |
| 306 | apt        | Java     | arm          | android  | Pegasus             |
+-----+------------+----------+--------------+----------+---------------------+
[+] Total records found: 8

mdb #> use 163
mdb andr0id_l0cker#> get
[!] Probably path name in git vs. sqlite does not match.
[!] Please try and go to https://github.com/ytisf/theZoo/raw/master/malwares/Source/Original/andr0id_l0cker/andr0id_l0cker.zip or report the malware ID so we can fix it.
mdb andr0id_l0cker#>

**Comment by ytisf** [comment]
Hey @zeeebbbrrraaa . The DB name did not match the location on disk. This was fixed. Thanks for your input.
