### ISSUE TITLE
i have problem with wannacry ransomware

### ISSUE THREAD

**Issue by ahmedubuntu** [ytisf/theZoo#136]
how i can add my btc address to this ransomware ?

**Comment by nrrpinto** [comment]
Funny guy! Don't spam the repository!

**Comment by Morsmalleo** [comment]
> how i can add my btc address to this ransomware ?now 
 close this issue as its spam

**Comment by SuperCraftAlex** [comment]
just open wannacry in a hex editor and change the btc adresees. But why do u need it

**Comment by ytisf** [comment]
Let's hope @ahmedubuntu was pulling a troll. 
Either way i think we can be sure this is not going to be WannaCry 3.0...
