### ISSUE TITLE
A small question.. !!⚠️

### ISSUE THREAD

**Issue by demonic004** [ytisf/theZoo#139]
Bro u said these are live and even try to infect and should use vm environment 

My question is if we unlock or extract the zip will it effect or infect android.... like just opening the zip not installing the apk😅😁

**Comment by viown** [comment]
it shouldn't unless you run them.

**Comment by Morsmalleo** [comment]
> Bro u said these are live and even try to infect and should use vm environment
> 
> My question is if we unlock or extract the zip will it effect or infect android.... like just opening the zip not installing the apk😅😁

No it won't, not unless you execute them

**Comment by Morsmalleo** [comment]
Close this issue as it has been resolved

**Comment by ytisf** [comment]
Please be caution about all malware here. Although decompressing them *should* not detonate any of them, we highly recommend decompressing them only at the safe and isolated environment.
