### ISSUE TITLE
How do you view source code? https://i.imgur.com/2PWtuQP.png

### ISSUE THREAD

**Issue by MiChaelinzo** [ytisf/theZoo#143]
**I'm kinda noob how do you guys recode the malwares or open it's code etc? I'm using Atom and Vscode, etc. It seems its using an alien programming language or cryptography when I unzip it and read its code? How to view the malwares samples, pdf, cont, txt., codes because I already clicked hundred times nothings happening?** 
<img width="425" alt="malwares" src="https://user-images.githubusercontent.com/68110223/90956122-2c6b3800-e48c-11ea-8799-c9d86938ec5b.PNG">
https://i.imgur.com/2PWtuQP.png

**Comment by balenol** [comment]
What you're opening right now is the "git" part of the virus. It doesn't do anything except track the changes inside of the folder (git is a version control). And please for the love of god, do not do anything funny like opening the virus up or something like that.

**Comment by MiChaelinzo** [comment]
> What you're opening right now is the "git" part of the virus. It doesn't do anything except track the changes inside of the folder (git is a version control). And please for the love of god, do not do anything funny like opening the virus up or something like that.
I'm running in linux/gnu and just opening android apk and windows x32 so I think I'm safe also
how can i have full access of the file inside the folder? i would like to study the code and prog. lang. of it.

**Comment by maxtinion** [comment]
dude it's a compiled binary you can't just open source closed source software..

**Comment by balenol** [comment]
@MiChaelinzo if you REALLY wanted to, just see anything under https://github.com/ytisf/theZoo/tree/master/malwares/Source and download some of the .rar inside of those folders to check the source code, whether it's reversed or original. Just be careful please, this repo is DEFINITELY not a "toy".

**Comment by ytisf** [comment]
Hey @MiChaelinzo ,
As @tengkuizdihar correctly mentioned, most of the samples in theZoo are compiled binary files. With few exceptions you cannot 'decompile' them (automatically reverse them to the original source code). However, there is a section of reversed/original source codes. 
Please be careful. Some of the codes have various trigger points and might detonate when loaded/built. If you're not sure about how to load a source code or compile these project i suggest you start with programming tutorials before attempting to edit malware source code. Even in VM this might be problematic as many VMs enable many sharing features between the host and VM for convenience by default and that might mean compromising your host machine. 
Safety first.
