### ISSUE TITLE
MALWARE ID: 177 - WannaCry_Plus --PROBLEM: Path name in git vs. sqlite does not match 

### ISSUE THREAD

**Issue by Morsmalleo** [ytisf/theZoo#147]
Please fix 

![Screenshot 2021-01-27 05:17:51](https://user-images.githubusercontent.com/64344168/105977499-6f46c280-605f-11eb-9372-0feca0a6dfce.png)

**Comment by ytisf** [comment]
Fixed in the latest commit :)
