### ISSUE TITLE
Request | New Malware | Houdini

### ISSUE THREAD

**Issue by CyRamos** [ytisf/theZoo#152]
Hey guys.
I'm building an overlap for a new analyst team and I'm searching for Trojan called Houdini. 
It's a malware coded on VB, I'm searching the obfuscating version as mention on the video below. 
Thanks.

https://www.youtube.com/watch?v=3Q9-X_NRlJc

**Comment by ytisf** [comment]
Hey @CyRamos , 
Looks like there are several Houdini malware out there. I found two in VBS (one pre-bundeled in a PE) but neither looked like the one in the video. Here's [one](https://github.com/AhmetHan/h-worm_houdini/blob/master/h-worm_houdini_vbs_rat_source_code) and here's the [other](https://www.fireeye.com/blog/threat-research/2013/09/now-you-see-me-h-worm-by-houdini.html). 
Let us know if one of these are the ones you meant as the obfuscation form seems different than the one on the video. 
Best of luck.
