### ISSUE TITLE
Is there a place I find neutralized samples of malware?

### ISSUE THREAD

**Issue by ZM-20-20** [ytisf/theZoo#154]
I want to demo how to perform malware reverse-engineering, but I'd rather not perform such on a live sample for the reason of that 'just in case' potential of things going wrong.

**Comment by ytisf** [comment]
Hey Zach, 
There are many places to start learning. [Corelan](https://www.corelan.be), [InfoSecInstitute](https://www.infosecinstitute.com/skills/learning-paths/malware-analysis-reverse-engineering/)  are just a few, (no affiliation at all) as well as some open source material and references such as [this one](https://reverseengineering.stackexchange.com/questions/265/where-to-find-free-training-in-reverse-engineering). 
In a similar manner to learning to fly or dive, there is some knowledge to be gained before actually climbing a plane or putting on your tanks. Start with reading, building a structure for your study, finding a mentor and slowly but surely when you the time comes you would want to dissect a malware you will already know how to do so and what are the precautions you'll need. 
Best of luck!
