### ISSUE TITLE
I looking for 5 DOS viruses

### ISSUE THREAD

**Issue by FirstBlood12** [ytisf/theZoo#156]
I am unable to find these 5 DOS Viruses: Rosebud, Phantom1, Red Scare, Brain and Stoned.
If someone can provide these viruses to me, I would be very thankful.

Rosebud:
https://www.youtube.com/watch?v=v62Qdo_WMlc

Red Scare:
https://www.youtube.com/watch?v=_1PrqhW5-ko

Phantom1:
https://www.youtube.com/watch?v=W724mb8xQXw

Brain: 
https://www.youtube.com/watch?v=nuzrxQgvJS0

Stoned:
https://www.youtube.com/watch?v=kfk4g0iPv74

Thanks in advance!

**Comment by ytisf** [comment]
Hey @FirstBlood12 , the Rosebud/Jerusalem malware seems to have had numerous iterations. Can you point us to the version which interests you? (https://malwiki.org/index.php?title=Jerusalem). 

Regarding Red Scare - we could not find any hashes relating to the samples or detection names. Could you provide them? 

Regarding the rest - the same. Any pointer would be helpful.

**Comment by FirstBlood12** [comment]
Thanks for the reply @ytisf, I am searching for the Jerusalem.Rosebud virus version.

**Comment by ytisf** [comment]
Hey @FirstBlood12 . Latest batch had Jerusalem in it and some other stuff. 
If there's any samples your were interested in and we've missed just let us know.
