### ISSUE TITLE
I'm looking for Cainxpii ransomware.

### ISSUE THREAD

**Issue by foxof4545** [ytisf/theZoo#162]
VT Sha256: cc19c3241f7e32532218b47a621622c832ba4cb34006a3729c76fc3d45a3de3d
Filename: Ransomware.exe

Demonstration video link: https://www.youtube.com/watch?v=7aAF3L6vqOc&ab_channel=Britec09

I'm looking for this to testing.

**Comment by ytisf** [comment]
Hey, This was added to the latest update. Enjoy your studies.
