### ISSUE TITLE
I am looking for UEFI ransomware

### ISSUE THREAD

**Issue by FirstBlood12** [ytisf/theZoo#168]
Virustotal link: https://www.virustotal.com/gui/file/aed230b6b772aeb5c25e9336086e9dd4d6081d3efc205f9f9214b51f2f8c3655/detection

I am looking for this ransomware for testing.

**Comment by n0tdUck** [comment]
https://www.hybrid-analysis.com/sample/aed230b6b772aeb5c25e9336086e9dd4d6081d3efc205f9f9214b51f2f8c3655
I've submitted the sample, check if you can download it.

**Comment by FirstBlood12** [comment]
Uhh, I can't, is there other way?

**Comment by ytisf** [comment]
Hey @FirstBlood12  - This will be added to the next theZoo release. I will post here when it comes out.

**Comment by n0tdUck** [comment]
@FirstBlood12, do you have an account? If yes, then the sample should be available to download.
https://www.hybrid-analysis.com/sample/aed230b6b772aeb5c25e9336086e9dd4d6081d3efc205f9f9214b51f2f8c3655?environmentId=120

**Comment by bidhata** [comment]
[4822747090944000.zip](https://github.com/ytisf/theZoo/files/7580554/4822747090944000.zip)
Here you are ...

**Comment by FirstBlood12** [comment]
Thanks!
