### ISSUE TITLE
REQUEST FOR NEW MALWARE UPLOAD: Mischa ransomware

### ISSUE THREAD

**Issue by FirstBlood12** [ytisf/theZoo#170]
Virustotal link:
https://www.virustotal.com/gui/file/eefa052da01c3faa1d1f516ddfefa8ceb8a5185bb9b5368142ffdf839aea4506/detection

Looking for this sample for testing purposes.

**Comment by bidhata** [comment]
Here you are. Password for the zip file is infected
[6008678934282240.zip](https://github.com/ytisf/theZoo/files/7670813/6008678934282240.zip)

**Comment by FirstBlood12** [comment]
Thanks!
