### ISSUE TITLE
Request Dino malware

### ISSUE THREAD

**Issue by jjjan** [ytisf/theZoo#18]
https://www.virustotal.com/en/file/7ba09403e9d7122a20fa510de11f7809822e6e11efb164414e2148b762cf4e75/analysis/

this is Dino malware cloud you upload on your malware repository

sorry for asking hear

thanks indeed

**Comment by ytisf** [comment]
Hey jjjan,
Looking into this now. Unfortunately VirusTotal subscription is very costly so will try other ways. Sent out some probes and wee how it goes. 
Leaving this topic open until we get a response.

**Comment by Sheksa** [comment]
Caught him.
Credit goes to the knowledgeable anonymous :)

**Comment by jjjan** [comment]
hello i found this sample if you need i can up for you
