### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by D4di69** [ytisf/theZoo#184]
Hello, i cloned the repository, i installed succefully the requirements with python and now typing 'python theZoo.py' the script shows this errors:
`Traceback (most recent call last):
  File "C:\Users\sussq\Desktop\theZoo\theZoo-master\theZoo.py", line 109, in <module>
    main()
  File "C:\Users\sussq\Desktop\theZoo\theZoo-master\theZoo.py", line 73, in main
    eulaHandler.prompt_eula()
  File "C:\Users\sussq\Desktop\theZoo\theZoo-master\imports\eula_handler.py", line 54, in prompt_eula
    eula_answer = raw_input(
NameError: name 'raw_input' is not defined`

**Comment by D4di69** [comment]
opened imports\eula_handler.py and mofidied line 54 from 'raw_input' to just 'input'

**Comment by geeksailor** [comment]
For those of you still having issues with the input on the EULA, check the version of Python you have installed. Make sure that you are using Python3 are running `python3 theZoo` not `python theZoo` if you have only 2.7 or both 2.7 and 3.x installed. Python2.7's reading input is different than 3's and causes issues.

To the dev team, not sure if you can throw a quick few lines in the next update to detect python version and if ran 2.7, make a second input method for that Python version so it can read the input? Or it closes the EULA with error to restart using python3? Just a suggestion :)
