### ISSUE TITLE
The 'ytisf/theZoo' repository doesn't contain the 'malware/Binaries/Raccoon.Stealer.v2/Raccoon.Stealer.v2.zip' path in 'master'.  

### ISSUE THREAD

**Issue by futures123-start** [ytisf/theZoo#201]

**Comment by futures123-start** [comment]
357 inexistence

**Comment by mrhenrike** [comment]
**Update from PR [#243](https://github.com/ytisf/theZoo/pull/243):** Fixed in PR#243 — Raccoon.Stealer.v2.sha.zip renamed to Raccoon.Stealer.v2.zip (bad .sha suffix was causing 404).
