### ISSUE TITLE
Bart Ransomware: Samples

### ISSUE THREAD

**Issue by caffeinewriter** [ytisf/theZoo#24]
Can't create a PR for this at the moment, but if it's not done by the time I have a chance, I'll throw one together. Seems like Dridex/Locky creators have been working on a new strain of Ransomware called Bart:

https://www.proofpoint.com/us/threat-insight/post/New-Bart-Ransomware-from-Threat-Actors-Spreading-Dridex-and-Locky

Bart Sample from Proofpoint's article:
[hxxps://summerr554fox[.]su/files/6kuTU1.exe]

Haven't tested to see if it's still live.
Looks like you might be able to get a sample of RockLoader as well, since that's the main dropper they use.

JavaScript Rockloader Payload, Use Extreme Caution:
[hxxp://camera-test.hi2[.]ro/89ug6b7ui?voQeTqDw=RUYEzU]

**Comment by AdamGreenhill** [comment]
Thanks for link! I'm always looking for new ransomware.

**Comment by caffeinewriter** [comment]
Ah darn, I didn't have a chance. I'll keep an eye out for new samples of it. I really want to dive into this one, since it doesn't connect to a C2 to encrypt.
