### ISSUE TITLE
Any of these can cause damage to HDD?

### ISSUE THREAD

**Issue by highacid** [ytisf/theZoo#26]
Hello,

I am looking for a client some tool to damage HDD.

**Comment by teknul** [comment]
You don't require tools here to achieve that. Are you trying to physically damage the drive? If you just want to damage data you have many out of the box tools... fdisk, dd,  dmcrypt, etc...

**Comment by apuentemedallia** [comment]
Besides a hammer you might find this one useful. By constantly wiping the
hard drive you reduce its life expectancy.

http://dban.org/download


-- 
*Best Regards,*

*Adrian Puente*
Information Security Engineer  |  ❖ Medallia, Inc.
Office: +1 (650) 485-1821
Email: apuente@medallia.com
PGP Key ID: 4D5848EF
Fingerprint: F55B AAE9 73D8 0DB7 BB03  46EF 7A8F 9C49 4D58 48EF
<http://medallia.com/>   <https://www.linkedin.com/company/medallia-inc.>
<http://blog.medallia.com/>  <https://twitter.com/medallia>
<https://www.facebook.com/medalliainc>
