### ISSUE TITLE
Errors when you run theZoo.py

### ISSUE THREAD

**Issue by blackalchemy** [ytisf/theZoo#29]
When you run the python file you get the following output:

  File "theZoo.py", line 85
    print vars.maldb_banner
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by Sheksa** [comment]
Currently theZoo.py does not support python 3, that might change in  the future but for now that is the issue.

**Comment by blackalchemy** [comment]
What is the supported python version?

**Comment by Sheksa** [comment]
2.7.X
