### ISSUE TITLE
How to use the malware source file

### ISSUE THREAD

**Issue by kellsea** [ytisf/theZoo#30]
Hi,

I wanted to know how to apply or use the malware source files given?

 http://ytisf.github.io/theZoo/

Thank You.

**Comment by Atavic** [comment]
By looking [here](https://github.com/techgaun/mirai), it seems he used [this](http://pastebin.com/1rRCc3aD).

**Comment by kellsea** [comment]
what is the password to use 1 of the malware zip file?

**Comment by neutt22** [comment]
`infected` is the default password

**Comment by jimmy4992** [comment]
Hi, I was wondering if anyone knows a tutorial on how to use these systems.

**Comment by neutt22** [comment]
Srsly bruh don't even try if you have no idea about programming esp. compiling these stuff

**Comment by zopy50** [comment]
you wanna know on how to run this systems? contact me

**Comment by zopy50** [comment]
you wanna know on how to run this systems? contact me here:email:wbank670@gmail.com

**Comment by karikalansaitechnology** [comment]
i want to compile this source code ytisf/theZoo due to education purpose please help me how to compile that code ..

**Comment by ApertureSecurity** [comment]
I haven't opened it up and looked. Look at the extension of file. If it's a .c or cpp then lookup the extension and see how to compile it.

If its c , then gcc will probably suffice. If cpp then visual studio will probably work.

**Comment by ahkhodja** [comment]
ZeuS2.0.8.9_Feb2013 how to configure screenshot in client
