### ISSUE TITLE
Licensing. 

### ISSUE THREAD

**Issue by LogoiLab** [ytisf/theZoo#36]
I don't know if you are technically allowed to put a general license on the repository. Even though malware is bad the authors still have copyright power. They probably will never issue any DMCA requests but just for correctness sake you might want to consider handling licensing differently.

**Comment by jesobreira** [comment]
What do you suggest? Remove licensing and putting a "Each malware may be licensed on its own way" warning instead?

My suggestion is [WTFPL](http://www.wtfpl.net/) 😛

**Comment by ytisf** [comment]
@LogoiLab , Any recommendation? None of us are lawyers and we are open to suggestions. Obviously, the license applies to our code only and not to any of the malwares as we have not written any of them.

**Comment by LogoiLab** [comment]
I would suggest editing the current license to exclude specific directories. Or include a license in every zip file staying that "this software comes as is with no license".

**Comment by Rourke101** [comment]
Really? I remember the old days, when we collected all this material and where none of this would have happened... Now we licence virii material :-D

If this is how people do things now I would have never guessed this future of extreme political correctness (with all my respect).

**Comment by ytisf** [comment]
Hey @LogoiLab  - With some delay but very much adopted. Thank you. 
A little shout out on the readme for this important comment.
