### ISSUE TITLE
ransomware study for educational purpose

### ISSUE THREAD

**Issue by karikalansaitechnology** [ytisf/theZoo#54]
i have tried to open in this folder(Ransomware.Locky.ZIP) it's need password if anyone knows password please send this is my mail id karikalan4692@gmail.com.

**Comment by aancw** [comment]
All password always stored in .pass file. 

https://github.com/ytisf/theZoo/blob/master/malwares/Binaries/Ransomware.Locky/Ransomware.Locky.pass

Password: `infected`
