### ISSUE TITLE
Unable to launch ransomware

### ISSUE THREAD

**Issue by gfraser78** [ytisf/theZoo#56]
I am wondering if someone can provide me some guidance.  I am trying to pull some ransomware to load on a VM for educational purposes.  I have tried a bunch of different types off https://github.com/ytisf/theZoo/tree/master/malwares/Binaries but none of them seem to load or do anything after they are extracted.  I get prompted for the password and the zip files take the password, but I cannot seem to get infected. :)

I am using a Windows 2012R2 vm with no Antivirus/Windows Defender.

I would have thought this would be easy.

Any help would be appreciated.
Thanks,
Greg

**Comment by James946** [comment]
To launch it rename the files inside the zip to something like test.bin.exe and run it. note there is no way to edit the ransomeware to add your own website/btc address

**Comment by jesobreira** [comment]
Also note that it's usual for malwares to detect and don't run on VM.

**Comment by gfraser78** [comment]
Thanks James946 & jesobreira.  Appreciate your responses.  Do you know of any ransomware that does work in VM's.  I have some spare physical machines I can infect, but VM's make roll back a whole lot easier.
Thanks,
Greg

**Comment by jesobreira** [comment]
You can use VPS services that also have the snapshot feature and access them through VNC or RDP. There are very cheap ones, starting from $7/mo. If you want my personal suggestion please provide a way to contact to avoid ads on github (if you're going to post your email, please replace @ with 'at' and then edit/delete it to avoid email crawlers/spam or consider using a mailinator temporary inbox).

**Comment by Anon0708** [comment]
You can run the file on an VM. Why should it not work? Tell me your error please, and we can fix it.

**Comment by skaspi** [comment]
I have the same issue: the ransomware doesn't run on Microsoft Azure VM (Windows Server 2016).
Did you manage how to solve this problem?
Thanks

**Comment by VVinner38** [comment]
@Anon0708 Some malware check if they're in a VM and if that's the case they don't execute to prevent them from being inspected.

**Comment by ytisf** [comment]
Hey. Some ransomware avoids sandboxing and some might be blocked by the VM you are attempting to detonate them on. We recommend a local isolated machine with a restore state for investigation.
