### ISSUE TITLE
'get' command is error 

### ISSUE THREAD

**Issue by w3sh** [ytisf/theZoo#67]
error get command
error get malware failed

**Comment by ytisf** [comment]
Please add some info...
I don't see this error happening here...

**Comment by isaacfiifi** [comment]
am getting this error
please help ..
"Error getting malware"

**Comment by danieleulice** [comment]
Hi,
I am getting the same error. My python version is 2.7.14+ and after execute the get command the error "[-] Error getting malware." appears.

Please help..

**Comment by ytisf** [comment]
apparently there were some mismatches from paths in sqlite vs actual paths. Fixed some and put a more informative error. Thanks for reporting these.

**Comment by danieleulice** [comment]
Hi,

Here is a more detailed error

"mdb #> use 177
mdb Wannacry+#> get
[!] Probably path name in git vs. sqlite does not match.
[!] Please try and go to https://github.com/ytisf/theZoo/raw/master/malwares/Binaries/Ransomware.Wannacry_Plus/Ransomware.Wannacry_Plus.zip or report the malware ID so we can fix it.
"

**Comment by tejorahul95** [comment]
get 
Downloading: Android.PegasusB.zip Bytes: 1096108
   1096108  [100.00%]

Downloading: Android.PegasusB.pass Bytes: 9
         9  [100.00%]

Downloading: Android.PegasusB.md5 Bytes: 59
        59  [100.00%]

[!] Probably path name in git vs. sqlite does not match.
[!] Please try and go to https://github.com/ytisf/theZoo/raw/master/malwares/Binaries/Android.PegasusB/Android.PegasusB.sha256 or report the malware ID so we can fix it.





plz solve this

**Comment by tejorahul95** [comment]
mdb #> use 311
mdb DarkHydrus#> get
[!] Probably path name in git vs. sqlite does not match.
[!] Please try and go to https://github.com/ytisf/theZoo/raw/master/malwares/Binaries/Coll.Coll.DarkHydrus/Coll.Coll.DarkHydrus.zip or report the malware ID so we can fix it.

**Comment by joumanaelsheikh** [comment]
Hello, I am trying to run some apts and none of their ids match too. I also tried other types but none worked. Still getting the "probably path name in git vs sqlit does not match". Please help

**Comment by alubeban** [comment]
has this been fixed???

**Comment by HouseMommy** [comment]
No

Thank you,
Duvelza M Saenz 'D'
Lead Associate
Data Analytics and Capabilities Cell Lead
Women in Cybersecurity (WiCyS) Member
3133 General Hudnell  Dr, Suite 110
San Antonio, Texas 78226
(O) 210-921-8758   (M) 210-589-6230
SIGNAL
***@***.***
***@***.******@***.***>
***@***.******@***.***>
“Your goal is not to convince people that you are brilliant, but that your solution is trivial.”

[BAH 100TH LOGO_black_red]

From: adham cahyo n ***@***.***>
Sent: Friday, April 8, 2022 3:58 PM
To: ytisf/theZoo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] Re: [ytisf/theZoo] 'get' command is error (#67)


has this been fixed???

**Comment by alubeban** [comment]
Wow, even though I like your product, you have a lot of problems lately, the good thing is that it used to be smooth when downloading

**Comment by flakowarhol** [comment]
Hi, I have this error, I tried all the ways to installation in Kali but all the errors are the same, can someone give a hand?

Traceback (most recent call last):
  File "/home/flakowarhol/Downloads/theZoo-master/./theZoo.py", line 109, in <module>
    main()
  File "/home/flakowarhol/Downloads/theZoo-master/./theZoo.py", line 73, in main
    eulaHandler.prompt_eula()
  File "/home/flakowarhol/Downloads/theZoo-master/imports/eula_handler.py", line 54, in prompt_eula
    eula_answer = raw_input(
NameError: name 'raw_input' is not defined

**Comment by GandharAcharya** [comment]
> Hi, I have this error, I tried all the ways to installation in Kali but all the errors are the same, can someone give a hand?
> 
> Traceback (most recent call last): File "/home/flakowarhol/Downloads/theZoo-master/./theZoo.py", line 109, in main() File "/home/flakowarhol/Downloads/theZoo-master/./theZoo.py", line 73, in main eulaHandler.prompt_eula() File "/home/flakowarhol/Downloads/theZoo-master/imports/eula_handler.py", line 54, in prompt_eula eula_answer = raw_input( NameError: name 'raw_input' is not defined

SAMEEEE!!!!
