### ISSUE TITLE
Ransomware.Petrwrap does nothing

### ISSUE THREAD

**Issue by m3a2r1** [ytisf/theZoo#68]
I'm trying to run Petrwrap ransomware but I can't. 
027cc450ef5f8c5f653329641ec1fed9.exe informs that is not correct Win32 app, myguy.hta and svchost.exe do nothing, files from .gz files looks like doc/rtf/exe file but do nothing too.
Ransomware.Petya works correctly, both bin files after changing extensions to exe do the job.
What am I doing wrong with Petrwrap?

**Comment by AnwarAlg** [comment]
I m facing the same issue as we speak, could it be a SandBox Detection technique?

**Comment by fsacer** [comment]
It's dll, first try to learn more about the malware before trying to run it-

**Comment by ApertureSecurity** [comment]
Just throwing this in here. 

If it's a dll then just use the 

`rundll.exe foo.dll #1`

And it should execute.

**Comment by Lodia12** [comment]
i have same problem , who can help
