### ISSUE TITLE
Ransomware jigsaw

### ISSUE THREAD

**Issue by smirk24** [ytisf/theZoo#69]
For the past few days ive been trying out ransomware because ive done a lot of pc repair well i stumbled a cross ransomware.jigsaw but i cant seem to figure out how to execute the jigsaw ransomware inside my virtualbox can some one help me out please?

**Comment by hmobrienv** [comment]
Have you tried renaming the file to have a .exe extension? 

You may also need to insure that you have the setting to show common file extensions on.

**Comment by smirk24** [comment]
Ive tried .exe .vbs .bin .sfx and it doesnt seem to work. Do i need to do something with the source code and the hash above the jigsaw zib file? Ill have to try the common file extension settings though

**Comment by smirk24** [comment]
I fixed it. I was trying it on xp sp2 on a virtual box without any of the updates installed but as soon as i tried in a fully updated windows 7 vb system it worked. Thank you for your help
