### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by rantony1** [ytisf/theZoo#75]
Is there a reason every time I try to run theZoo.py python crashes in Windows?

**Comment by ytisf** [comment]
Have you found our easter egg?

**Comment by bararchy** [comment]
@ytisf LOL 
@rantony1 an error message might help

**Comment by rantony1** [comment]
The Error message is "The python.exe has stopped working"

**Comment by CrazyLlama** [comment]
@rantony1 This is just a straight up repo of malware, no safety to be found here. Have a read through the python script to see what it does, it's commented 😄 

https://github.com/ytisf/theZoo/blob/master/theZoo.py
