### ISSUE TITLE
Androrat password

### ISSUE THREAD

**Issue by Gladuin** [ytisf/theZoo#76]
The password of the .zip on this github is "infected" as usual but there is a .rar file in that .zip that also has a password...

I have tried these passwords: AndroRat, AndroRAT, androrat, androrat.rar and ANDRORAT.

These were all wrong.

I hope that someone has the password and can solve this issue.

**Comment by TheBarret** [comment]
Confirmed, most passwords don't work.

**Comment by Axe-Usa** [comment]
1234

**Comment by ytisf** [comment]
Commit 7dba877ca5c464d9dc5910c71cbafba23c5bfc9b fixes this. thanks

**Comment by ankeshsutariya** [comment]
i have password if you are still looking?? or you have been cracked it??

**Comment by vanshhbh** [comment]
What's that??
