### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by kushal-17** [ytisf/theZoo#92]
Sorry sir its not issue, can you help me to get KRONOS trojan because i'm not able to fing in dark web plzz can u help to provide me that,in case for exchange i have atom payload bulider a.k.a shark ransomware if it is satisfactory to you.

THANK YOU:-
-KUSHAL

**Comment by ytisf** [comment]
If you want I have block-chain based super computer trojan that can rat any machine.
Willing to trade it for a jar of pickles. If you're able to get one just DM me on Jabber. 

Yeah... Nope.
