### ISSUE TITLE
Run Petrwrap 

### ISSUE THREAD

**Issue by supermanMTA** [ytisf/theZoo#99]
I'm trying to run Petrwrap ransomware but I can't. 027cc450ef5f8c5f653329641ec1fed9.exe is a dll file. How to run it?

**Comment by jesobreira** [comment]
Have you tried rundll32?

**Comment by supermanMTA** [comment]
I tried with Rundll32. It works but it does not automatically shutdown. Do you analyse it? Can you support me?

**Comment by RestaurantController** [comment]
It doesn't automatically shutdown the computer

**Comment by ytisf** [comment]
Hey @supermanMTA - You can attempt to run it in a properly isolated VM with `rundll32.exe` which should be able to execute it.
